In [1]:
import numpy as np
import cv2
import pickle
from keras.optimizers import Adam
from keras.layers import Conv2D,Dense,Activation,Flatten,MaxPooling2D,Input,Lambda,Dropout
from keras.models import Model,load_model
import scipy

In [2]:
Model?

In [2]:
path = "C:\\Users\\YASH\\Cifar-10\\aftquan.h5"
cifar=load_model(path)

In [3]:
cifar.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
lambda_2 (Lambda)            (None, 32, 32, 3)         0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 32, 32, 64)        1792      
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 32, 32, 64)        36928     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 16, 16, 128)       73856     
_________________________________________________________________
dropout_3 (Dropout)          (None, 16, 16, 128)       0   

In [4]:
data=np.load('C:\\Users\\YASH\\Cifar-10\\cifar_data.npy')
train_x=data[0:55000]
test_x=data[55000:]
label=np.load('C:\\Users\\YASH\\Cifar-10\\cifar_label_onehot.npy')
train_label=label[0:55000]
test_label=label[55000:]

In [37]:
count=0
for layers in cifar.layers:
    if 'conv2d' in layers.name or 'dense' in layers.name:
        a=cifar.get_layer(layers.name)
        e=a.get_weights()
        if(len(e)>0):
            c=np.asarray(e[0])
            g=(c>0.1)
            f=(c<-0.1)
            c=c*(g+f)
            count= np.sum(c==0)+count
            e[0]=c
             a.set_weights(e)

In [35]:
opt=Adam(lr=0.001)
cifar.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
cifar.fit(train_x,train_label,epochs=2,validation_split=0.05,batch_size=32)

Train on 52250 samples, validate on 2750 samples
Epoch 1/2
52250/52250 [==============================] - 158s 3ms/step - loss: 0.5615 - accuracy: 0.8105 - val_loss: 0.7189 - val_accuracy: 0.7829
Epoch 2/2
52250/52250 [==============================] - 168s 3ms/step - loss: 0.5171 - accuracy: 0.8288 - val_loss: 0.7150 - val_accuracy: 0.7738


In [103]:
cifar.evaluate(x=test_x,y=test_label)

5000/5000 [==============================] - 4s 726us/step


[0.5564912418365479, 0.8226000070571899]

In [105]:
#prunning (0.01:-0.01)
cifar.evaluate(x=test_x,y=test_label)

5000/5000 [==============================] - 3s 662us/step


[0.5531226119041442, 0.8226000070571899]

In [108]:
#prunning (0.01:-0.01) and training(1 epoch)
cifar.evaluate(x=test_x,y=test_label)

5000/5000 [==============================] - 3s 656us/step


[0.6368430412292481, 0.7972000241279602]

In [36]:
#prunning (0.01:-0.01) and training(2 epoch)
cifar.evaluate(x=test_x,y=test_label)

5000/5000 [==============================] - 3s 562us/step


[0.6933112190246582, 0.7770000100135803]

In [29]:
#prunning (0.01:-0.01) and training(4 epoch)
cifar.evaluate(x=test_x,y=test_label)

5000/5000 [==============================] - 3s 547us/step


[0.713718020439148, 0.7942000031471252]

In [26]:
count

8488601

In [31]:
count

8551552

In [33]:
count

8551552

In [17]:
count

7359678

In [38]:
count

8570956

In [106]:
a=cifar.get_layer('conv2d_63')
e=a.get_weights()
e

[array([[[[-0.05973978, -0.04875761,  0.        , ...,  0.0384384 ,
            0.09493604, -0.04457916],
          [ 0.01104068,  0.        ,  0.01110658, ..., -0.        ,
           -0.01306281, -0.        ],
          [ 0.01342402,  0.        , -0.        , ...,  0.01891098,
           -0.        ,  0.        ],
          ...,
          [ 0.        , -0.01237017, -0.12586619, ..., -0.        ,
            0.2020598 ,  0.01984253],
          [ 0.01196202,  0.01022981, -0.02594635, ..., -0.02935059,
           -0.09938905, -0.0104232 ],
          [ 0.01111348, -0.05919366,  0.05123175, ..., -0.03017663,
            0.0649349 , -0.        ]],
 
         [[ 0.02161711, -0.01802213,  0.142558  , ..., -0.02308251,
           -0.03722898,  0.02324911],
          [ 0.01720537, -0.01070361,  0.        , ...,  0.02902171,
           -0.        , -0.03148798],
          [-0.01182692, -0.01649527,  0.        , ..., -0.01154474,
            0.        ,  0.02677077],
          ...,
          [-0

In [115]:
a=cifar.get_layer('conv2d_63')
e=a.get_weights()
e

[array([[[[-5.97397797e-02, -4.87576090e-02, -4.71190885e-02, ...,
            3.84384021e-02,  1.70485139e-01, -4.45791557e-02],
          [ 1.10406848e-02,  0.00000000e+00,  1.11065777e-02, ...,
           -0.00000000e+00, -1.30628143e-02, -0.00000000e+00],
          [ 1.34240203e-02,  0.00000000e+00, -0.00000000e+00, ...,
            1.89109799e-02, -0.00000000e+00,  0.00000000e+00],
          ...,
          [ 0.00000000e+00, -1.23701748e-02, -1.82934865e-01, ...,
           -0.00000000e+00,  2.59948462e-01,  1.98425259e-02],
          [ 1.19620189e-02,  1.02298101e-02, -3.40205021e-02, ...,
           -2.93505900e-02, -1.47836551e-01, -1.04232021e-02],
          [ 1.11134816e-02, -5.91936633e-02,  7.81134516e-02, ...,
           -3.01766284e-02,  2.61903089e-02, -0.00000000e+00]],
 
         [[ 2.16171071e-02, -1.80221274e-02,  3.95898521e-02, ...,
           -5.23221865e-02, -1.95265710e-02, -2.47291662e-02],
          [ 1.72053706e-02, -1.07036112e-02,  0.00000000e+00, ...,
     

In [37]:
a=cifar.get_layer('dense_16')
e=a.get_weights()

In [38]:
e

[array([[-0.05116335, -0.04357654, -0.06589945, ...,  0.04176069,
         -0.23963627, -0.21575668],
        [-0.24800837, -0.07763601,  0.06648641, ..., -0.06569561,
          0.04735057, -0.05641786],
        [ 0.06767458, -0.02421735, -0.05637228, ...,  0.10539347,
          0.01543923, -0.        ],
        ...,
        [ 0.1265378 ,  0.        , -0.0633262 , ...,  0.12363406,
         -0.02144257, -0.06072609],
        [-0.01444967,  0.1578801 , -0.14926274, ..., -0.02862873,
          0.10106341,  0.06197909],
        [ 0.        , -0.12054081, -0.10634176, ...,  0.13733403,
          0.17455786, -0.01173817]], dtype=float32),
 array([ 0.01290851, -0.16180706, -0.0291341 ,  0.17720038,  0.0189373 ,
        -0.03241292,  0.05081983, -0.01598063, -0.09428643,  0.06079563],
       dtype=float32)]

In [6]:
c=np.asarray(e[0])

In [123]:
g=(c>0.01)
f=(c<-0.01)

In [125]:
c=c*(g+f)

In [126]:
e[0]=c

In [128]:
a.set_weights(e)

In [103]:
c=((np.asarray(a.get_weights()))[0])

In [111]:
a=(c>0.01)
b=(c<-0.01)

In [97]:
a+b

array([[ True, False,  True,  True,  True],
       [ True,  True, False, False,  True]])

In [112]:
d=c*(a+b)

In [62]:
2359296-1014163

1345133

In [105]:
np.sum(c>0)

1040384

In [106]:
np.sum(c<0)

1318912

In [113]:
np.sum(d>0)

669476

In [114]:
np.sum(d<0)

943887

In [116]:
cifar.save('try2.h5')

In [8]:
c

array([[[[ 0.        ,  0.        , -0.        , ..., -0.01003632,
          -0.02477202, -0.        ],
         [ 0.        ,  0.        , -0.        , ...,  0.01738696,
           0.        ,  0.01492595],
         [ 0.        , -0.01483879,  0.01968181, ...,  0.        ,
          -0.01523904,  0.02327206],
         ...,
         [-0.02883567,  0.        , -0.0119992 , ..., -0.        ,
          -0.        ,  0.        ],
         [-0.04846879, -0.02063238,  0.01821643, ..., -0.02690401,
          -0.03130249, -0.03339496],
         [-0.        , -0.02746972,  0.02098945, ..., -0.01465223,
          -0.02313111, -0.        ]],

        [[-0.02066565,  0.01187956, -0.        , ...,  0.02511016,
           0.        , -0.02281213],
         [ 0.        ,  0.01077962, -0.02869654, ...,  0.02101103,
          -0.07770028, -0.01135988],
         [-0.01763438, -0.02861232, -0.02153413, ..., -0.01529612,
          -0.01475688, -0.01868185],
         ...,
         [-0.06241867, -0.        

In [14]:
for layers in cifar.layers:

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
